description = "production mode"
deploy_to = "/var/www/production"
scm = "git"
repo_url = "http://github.com/chaos.git"
branch = "master"
linked_files = ["config.toml", "nginx.conf"]
linked_dirs = ["logs", "public", "tmp"]
keep_releases = 5
tmp = "/tmp"
debug = true
keys = [".ssh/id_rsa"]

[default_env]
  created = "2016-07-04 11:49:26.515497534 -0700 PDT"

[roles]
  app = ["deploy@localhost"]
  db = ["deploy@localhost"]
  web = ["deploy@localhost"]
